const legacyRoutes={'programacio/planificacio-docent':'planificacio-docent','programacio/planificacio-ra1':'planificacio-ra1','programacio/planificacio-ra2':'planificacio-ra2','ra2-pla':'planificacio-ra2','ra2-apunts/r2-llicencies':'competencia-digital/digital-llicencies'};if(legacyRoutes[location.hash.slice(1)])location.replace('#'+legacyRoutes[location.hash.slice(1)]);
function route(){const alias=legacyRoutes[location.hash.slice(1)];if(alias){location.replace('#'+alias);return;}const bits=location.hash.slice(1).split('/'),key=bits[0]||'inici',anchor=bits[1];const panel=document.getElementById(key)||document.getElementById('inici');document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x===panel));document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+key+(anchor?'/'+anchor:'');a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');if(active){let p=a.parentElement;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}}});document.querySelectorAll('#teoria > article, #ra2-apunts > article, #ra3-apunts > article, #ra4-apunts > article').forEach(a=>a.hidden=a.parentElement.id===key&&!!anchor&&a.id!==anchor);selectProgrammeRA(key,anchor);if(anchor){requestAnimationFrame(()=>document.getElementById(anchor)?.scrollIntoView())}else window.scrollTo(0,0);document.title=panel.dataset.title+' · M0226';}window.addEventListener('hashchange',route);route();document.getElementById('print').addEventListener('click',()=>window.print());function calc(){const w=Number(document.getElementById('watts').value),pf=Number(document.getElementById('pf').value),reserve=Number(document.getElementById('reserve').value);const result=document.getElementById('result');if(!(w>0&&pf>0&&pf<=1&&reserve>=0&&reserve<=50)){result.textContent='Introdueix una càrrega positiva, un factor entre 0 i 1 i una reserva entre 0 i 50%.';return}const f=1-reserve/100;result.textContent=`Mínim de selecció: ${(w/f).toLocaleString('ca-ES',{maximumFractionDigits:1})} W i ${(w/pf/f).toLocaleString('ca-ES',{maximumFractionDigits:1})} VA. Cal complir els dos límits i verificar l’autonomia a la fitxa del fabricant.`}document.querySelectorAll('.calc input').forEach(x=>x.addEventListener('input',calc));calc();

const form=document.getElementById('teacher-login'), target=document.getElementById('teacher-content'),lock=document.getElementById('teacher-lock');
form.addEventListener('submit',async e=>{e.preventDefault();const message=document.getElementById('teacher-message');message.textContent='Obrint…';try{const r=await fetch('teacher.enc.json');if(!r.ok)throw Error();const data=await r.json();const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(document.getElementById('teacher-key').value),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:bytes(data.salt),iterations:data.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(data.iv)},key,bytes(data.cipher));target.innerHTML=new TextDecoder().decode(plain);alignTeacherContent(target);form.hidden=true;lock.hidden=false;document.getElementById('teacher-key').value='';message.textContent='';}catch(err){message.textContent='No s’ha pogut obrir. Comprova la contrasenya i la connexió.';}});
lock.addEventListener('click',()=>{target.replaceChildren();lock.hidden=true;form.hidden=false;});
window.addEventListener('hashchange',()=>{if(location.hash.split('/')[0]!=='#professorat')lock.click();});

function alignTeacherContent(root){
 const old=root.querySelector('#pla-docent');
 if(old){const note=document.createElement('p');note.innerHTML='<a href="#planificacio-docent">Consulta la planificació docent vigent de RA1, RA2, RA3 i RA4</a>.';old.replaceWith(note);}
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 while(node=walker.nextNode()){node.textContent=node.textContent.replace(/1\.([a-k])\s*\/\s*CA\d+/g,'1.$1').replace(/CA\s*(\d{1,2})(?![\d.])/g,(_,n)=>'1.'+String.fromCharCode(96+Number(n)));}
 const notice=document.createElement('p');notice.textContent='Els criteris *1.j i *1.k tenen activitats i registre independents a Avaluació de competències digitals. Les rúbriques històriques d’aquest material privat no en determinen la qualificació.';root.prepend(notice);
}

function selectProgrammeRA(key,anchor){
 if(key!=='programacio')return;
 const selected=/^programacio-ra[1-5]$/.test(anchor||'')?anchor:'programacio-ra1';
 document.querySelectorAll('#programacio-ra-curriculum > article').forEach(a=>a.hidden=a.id!==selected);
 document.querySelectorAll('#programacio-ra-curriculum [role="tab"]').forEach(a=>{const on=a.getAttribute('aria-controls')===selected;a.setAttribute('aria-selected',String(on));a.tabIndex=on?0:-1;});
}
document.querySelector('#programacio-ra-curriculum [role="tablist"]').addEventListener('keydown',e=>{
 const tabs=[...e.currentTarget.querySelectorAll('[role="tab"]')];const i=tabs.indexOf(document.activeElement);if(i<0)return;
 let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;
 e.preventDefault();tabs[next].focus();location.hash=tabs[next].hash;
});
